### ISSUE TITLE
Kos nnet

### ISSUE THREAD

**Issue by Ninjacoderhsi** [tyron12233/CodeAssist#123]
![Screenshot_۲۰۲۲۰۱۰۱-۱۴۴۴۳۶_CodeAssist](https://user-images.githubusercontent.com/89408667/147849343-7de3b86c-36c0-435c-b0ad-18740ae7b13a.jpg)

خاک تو سرت کنن حروم زاده نژاد پرست نمیتونی یک برنامه هم ایجاد کنی کسخل کیری فیس
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by Iyxan23** [comment]
I'm not sure what you're saying here, but it seems like you don't have kotlin stdlib added as a dependency. Kotlin wouldn't be able to function properly without it.

try adding
```gradle
implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.5.21'
```
in the `dependencies` block on `app/build.gradle`

**Comment by tyron12233** [comment]
The error is pretty self explanatory, your don't have the kotlin stdlib (which can easily be fixed by adding it through the library manager). Also, do not use offensive words (read the [repo's code of conduct](https://github.com/tyron12233/CodeAssist/blob/311a0ae4e6b0c82f99705b82cf8fb26c88ac052b/CODE_OF_CONDUCT.md)) if you do it again you will be banned from the repo.
