### ISSUE TITLE
Work needed for desktop platforms

### ISSUE THREAD

**Issue by axel358** [tyron12233/CodeAssist#30]
libaapt crashes on x86 with : Illegal instruction

The layout previewer incorrectly display elements on large landscape screens, content appears displaced to the right

Building a debug apk fails cuz it says module.aab it's already in there

Min api 26 it's a little high, maybe some work could be done to lowering it

**Comment by tyron12233** [comment]
Can you show the full log for aapt2? I have run some tests on x86 and it was passing for me.

Can you show the expected result vs the actual result in the preview?

It will be fixed in the future version, thanks.

Most of the compilers i ported such as `kotlinc` and `javac` uses `java.nio.**` classes and its not available on API 26 and below. Its possible to port `java.nio` but it will be a lot of work.

**Comment by axel358** [comment]
![100133600390_37356](https://user-images.githubusercontent.com/72220889/144177115-a7acef45-ce38-46a8-890d-a99ee7a33e45.jpg)
![Screenshot_20211130-120915](https://user-images.githubusercontent.com/72220889/144177144-3ddbdb08-c2af-4a1e-be12-a1dc42b035e8.png)

**Comment by axel358** [comment]
As u can see on portrait it displays correctly but in landscape that happens. Thanks for replying and keep up the good work

**Comment by axel358** [comment]
How hard would It be the task of porting java.nio?, I'd like to help

**Comment by tyron12233** [comment]
take a look at https://github.com/zhanghai/AndroidRetroFile, you would have to replace that for the entire project. i havent tested it yet
