### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by PharaohMod** [tyron12233/CodeAssist#326]
![Screenshot_2022-03-13-19-49-03-500_com tyron code](https://user-images.githubusercontent.com/70447547/158061289-9be601aa-0e46-46df-b96b-173c8ac1819f.jpg)
How can i fix this?

**Comment by 738631760** [comment]
有问题，编译不了

**Comment by tyron12233** [comment]
This usually happens if you create a kotlin class in a java project. To enable kotlin for that project, you need to add to kotlin stdlib dependency in the project manager. 

Group ID: `org.jetbrains.kotlin`
Artifact ID:  `kotlin-stdlib`
Version: `1.6.10`

Note: use version 1.6.10 since that's the version of the kotlin compiler CodeAssist uses.

**Comment by PharaohMod** [comment]
Thanks
