### ISSUE TITLE
Bug with versionCode and versionName

### ISSUE THREAD

**Issue by rfrizov** [tyron12233/CodeAssist#36]
There is a bug. If you import an existing project and start changing android:versionCode and android:versionName in the manifest, then when installing the application for some reason the version becomes 1.0

P.S. the question is this. Maybe it's better to make the SDK versions and application versions configured in build.gradle? It's more convenient this way

**Comment by tyron12233** [comment]
The version code and version name are currently hardcoded this way as currently I do not have a way of parsing groovy files except for using regex which is not reliable.

**Comment by rfrizov** [comment]
> The version code and version name are currently hardcoded this way as currently I do not have a way of parsing groovy files except for using regex which is not reliable.

But what about it? I don't want the app version to be 1.0, because it has an auto-update that compares the versions

**Comment by rfrizov** [comment]
It's just that when I create a new project in CodeAssist, I change the versionName and Code in the manifest, after the build, the version changes.

But if you import a project in which the build was done by build.gradle, and then add the versionCode and Name fields to the manifest, then after the assembly it turns out that the data from the manifest is not read, or the value of these fields is ignored. How is that?

**Comment by tyron12233** [comment]
The version name is currently hardcoded in [ManifestMerger](https://github.com/tyron12233/CodeAssist/blob/139ce3255d674c6bcb8bf0459f76f5aba8009ce0/build-logic/src/main/java/com/tyron/builder/compiler/manifest/ManifestMergeTask.java#L94). because it causes errors on projects that does not contain version code and version name. It requires effort to work on this so I decided to hardcode it for now. 

The reason why it works on a new empty project is that the manifest merger is skipped if the project has no libraries.

**Comment by tyron12233** [comment]
You can now change the `versionName` and `versionCode` in `app_config.json`
